<?php

/**
 * Add use-ajax class to each link in the pager.
 *
 * Implements hook_preprocess_pager().
 */
function reqresimport_users_preprocess_pager(&$variables): void {
  // dump($variables);
  // Make sure we only add the class to our pager.
  if ($variables['pager']['#route_name'] !== 'reqresimport_users.refresh_table') {
    return;
  }
  if (isset($variables['items'])) {
    foreach ($variables['items']['pages'] as &$page) {
      $page['attributes']->addClass(['use-ajax', 'pager-link']);
      }
  }
  if (isset($variables["items"]["next"])) {
    $variables["items"]["next"]["attributes"]->addClass(['use-ajax', 'pager-link']);
  }
  if (isset($variables["items"]["previous"])) {
    $variables["items"]["previous"]["attributes"]->addClass(['use-ajax', 'pager-link']);
  }
  if (isset($variables["items"]["first"])) {
    $variables["items"]["first"]["attributes"]->addClass(['use-ajax', 'pager-link']);
  }
  if (isset($variables["items"]["last"])) {
    $variables["items"]["last"]["attributes"]->addClass(['use-ajax', 'pager-link']);
  }
}
