block.settings.reqresimport_users_block:
  type: block_settings
  label: 'Reqres users block'
  mapping:
    per_page:
      type: integer
      label: Items per page
    email_label:
      type: string
      label: Email label
    forename_label:
      type: string
      label: Forename label
    surname_label:
      type: string
      label: Surname label

# Schema for the configuration files of the Reqres import - users module.
reqresimport_users.settings:
  type: config_object
  label: 'Reqres import - users settings'
  mapping:
    default_url:
      type: string
      label: 'Default URL for reqres users'
    default_endpoint:
      type: string
      label: 'Default endpoint'
