block.settings.reqresimport_users_block:
  type: block_settings
  label: 'Reqres users block'
  mapping:
    example:
      type: string
      label: Example

# Schema for the configuration files of the Reqres import - users module.
reqresimport_users.settings:
  type: config_object
  label: 'Reqres import - users settings'
  mapping:
    example:
      type: string
      label: 'Example'

block.settings.reqresimport_users_test_block:
  type: block_settings
  label: 'Test block block'
  mapping:
    example:
      type: string
      label: Example
